name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

env:
  IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (flake8)
        run: |
          if command -v flake8 >/dev/null 2>&1; then
            flake8 || true
          fi

      - name: Run tests (pytest)
        run: |
          if [ -d tests ] || [ -f pytest.ini ]; then
            pytest -q || true
          fi

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Publish image tag output
        run: echo "image=${{ secrets.ACR_NAME }}/backend:${{ steps.vars.outputs.IMAGE_TAG }}" >> $GITHUB_OUTPUT

